### ISSUE TITLE
What do we need to do to turn this into a plugin for choo?

### ISSUE THREAD

**Issue by yoshuawuyts** [colingourlay/chooet#2]
What are the hurdles to turn this into a `plugin` for choo? Which parts are currently incompatible? Which hooks are we missing?

Having a clear picture of the existing constraints would allow us to solve them. Thanks! :sparkles:

cc/ @colingourlay

**Comment by colingourlay** [comment]
Alright, before I dig deeper, I'd better outline the purpose of [duet](https://github.com/colingourlay/duet) and what it solves.

In a nutshell, a duet app is a single JS bundle which is executed in the page, and then re-executed in a web worker (I know, silly, right?). Duet itself is a communication bridge between the worker context and the main context, so that everything that can possibly run in a worker runs there, and external APIs such as the DOM, history, storage, etc. can be accessed seamlessly over these bridges.

The advantage of this is that you can (almost) stop thinking about where your code is working, because all of these bridges are transporting data around asynchronously, and the main thread is doing as little as possible so that DOM updates and transitions/animations are as jank free as possible.

OK, now onto your question...

The biggest blocker having choo run inside a web worker is that it depends on bel/morphdom which construct and manipulate DOM directly. This just isn't possible, which means that either:

1. A virtual DOM must be used inside the worker thread, with serialised DOM patches being passed over the thread (which chooet currently does), or
2. State changes are passed over the bridge and all of the DOM creation/diffing is done in the main thread (slightly defeating the purpose of duet to do as little in the main thread as possible).

If we go with (1), choo will need to have hooks to allow replacing yo-yo with a virtual DOM creation/diffing library; I'm assuming this will hook into the sheet-router view resolution and root node creation stages. If we go with (2), choo will need similar hooks, but they'd be for injecting the cross-thread channel into the route resolution step after reducers have run.

I'm really excited that we're trying to take an excellent app pattern like choo and apply it to multi-threaded apps, and hope something comes out of this discussion, even if a marriage of choo and duet isn't the right answer!

Also, please invite people who you think have good ideas around this! I'd love to know what they think.

cc/ @yoshuawuyts

**Comment by yoshuawuyts** [comment]
@colingourlay it's taken me a while to let this all sink in, and think I can formulate some thoughts now. What I'm curious about is if we could get [min-document](https://github.com/Raynos/min-document) nodes to render reliably into a worker and be transferrable between threads. If that's possible then we wouldn't need to rely on `virtual-dom` and all of its stuff but could keep passing pretend nodes around - and the whole conversion would become easier.

I love the work you've been doing by the way; can't express enough how impressed I am and excited to see where we could end up :heart:

**Comment by colingourlay** [comment]
@yoshuawuyts oh, wow. Now you've given me a lot to process and let sink in. while I'm doing that, here's a (loaded) question):

I'm not familiar with [min-document](https://github.com/Raynos/min-document), but after having a quick adventure through the source, I think I'm beginning to see where you're coming from. Are you hoping that a 'DOM' created by this library will look like a duck to `morphdom`? Event handling is always gonna be the biggest issue, as you can't serialise functions to transport them in/out of a worker, so there'll always have to be some kind of reference-based substitution (which is what `duet-virtual-dom` wrapper currently does).

I'm not sure the above even looks like a question, now that I've rambled on for a bit, but it's all stuff to think about. I'm also super excited to see this idea take shape and become something that devs can really benefit from 🎊

**Comment by colingourlay** [comment]
@nolanlawson, I know you're on GitHub vacation just now, so please ignore this for now (or entirely - I know you're suuuper swamped at the best of times).

You've done some awesome work around serialising DOM representations to/from workers, so I'd love to get your thoughts on what would be the best way to approach this if we were starting from scratch, rather than building upon something like `virtual-dom`.

I'm of the opinion that we should be trying to do everything we possibly can inside a web worker, including view rendering/diffing, but this becomes hard when you're trying to keep library size to a minimum, and the biggest saving we can make is dropping large virtual DOM libraries in favour of actual DOM diffing, a la [morphdom](https://github.com/patrick-steele-idem/morphdom)).

**Comment by yoshuawuyts** [comment]
> Event handling is always gonna be the biggest issue, as you can't serialise functions to transport them in/out of a worker, so there'll always have to be some kind of reference-based substitution (which is what duet-virtual-dom currently does)

Hmmmmmmmmmmmmmmmmmm, yeah that's a very good point. It seems [min-document doesn't have Element.addEventListener()](https://github.com/Raynos/min-document/search?utf8=%E2%9C%93&q=addevent&type=Code) either - even stuff like onclick is missing. So yeah if we're going to be rendering fake nodes, references seem like the logical option.

Feels like we're treading slightly into creating our own vdom abstraction, and I think that's fine. Using `morphdom`'s hooks we could perhaps extend the [event copy function from yo-yo](https://github.com/maxogden/yo-yo/blob/master/index.js#L18-L35) to also handle our own cool fake events; perhaps set a value of `Node.events = { eventName: [] }` or something? idk - definitely food for thought hey

**Comment by nolanlawson** [comment]
Yeah, I punted on the problem of event listeners whenever I used worker vdom. Instead I just attached a delegate listener and then made my mutations below the delegate.

**Comment by colingourlay** [comment]
@nolanlawson thanks for your input! I had a feeling that'd be the case, so consensus helps a lot. 

Welcome back 😄
